

    std::string ssqlInsertOrderExecution = ""
    " INSERT INTO `db_tickts`.`orderexecutions` "
    "        (  `id`,               "
    "           `orderid`,          "
    "           `exec_vol`,         "
    "           `exec_price`,       "
    "           `contrahent`,       "
    "           `ts`,               "
    "           `instant`,          "
    "           `ifid`,             "
    "           `uniqueid`,         "
    "           `currency_spot`,    "
    "           `openclose`,        "
    "           `fees`,             "
    "           `calcfee`,          "
    "           `stateid`,          "
    "           `flags`,            "
    "           `mifid_tvtic`,      "  
    "           `mifid_waiver`,     "
    "           `exchangetradeid`,  "
    "           `exchangeorderid`)  "
    "    VALUES     "
    "        (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)				"
    "   ";

    
    std::string ssqlSelectOrders = " "
    " SELECT      o.*"
    "                  , il.name AS productname"
    " FROM         tradedb.orders o"
    " LEFT JOIN    quotedb.isinlist il ON o.isin = il.isin"
    " WHERE        o.id IN (SELECT     oe.orderid"
    "                       FROM       tradedb.orderexecutions oe"
    "                       WHERE      oe.id > ? "
    "                       AND        oe.id <= ? "
    "                       GROUP BY   oe.orderid"
    "                       ORDER BY   oe.orderid ASC)"
    " ORDER BY     o.id ASC;";

    std::string ssqlInsertOrders = " "
    "	INSERT INTO `db_tickts`.`orders`"
    "	(   `id`,"
    "		`isin`,"
    "		`productname`,"
    "		`market`,"
    "		`ifmarket`,"
    "		`account`,"
    "		`user`,"
    "		`created`,"
    "		`created_instant`,"
    "		`dest`,"
    "		`currency`,"
    "		`symbol`,"
    "		`mspid`,"
    "		`comment`,"
    "		`externid`,"
    "		`type`,"
    "		`completed`,"
    "		`instrumenttype`,"
    "		`ocogroup`,"
    "		`otogroup`,"
    "		`groupid`,"
    "		`grouptype`,"
    "		`pricefactor`)"
    "	VALUES"
    "		(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
    "	ON DUPLICATE KEY UPDATE completed = ?	";                                   
